### ISSUE TITLE
无法启动，日志如下

### ISSUE THREAD

**Issue by hq262866869** [ipfs-force-community/filscan-backend#13]
./filscan_lotus 
[debug][2006-01-02 15:04:05] connect lotus success,peerId=12D3KooW9w6vy5Be5oYwLdxE3DFZyY439KpVQEEwttNMvHjnojyZ
filscaner:››››››››››››››››››››init_miner_states››››››››››››››››››››
 models_set_index_and_load_histroy, used_time = 0(s)
 models_set_index_and_load_histroy, used_time = 0(s)
filscaner:››››››››››››››››init_miner_states finished, time_used=0(s)!!!››››››››››››››››
2020-11-20T11:22:22.692+0800	INFO	filscan-backend/main.go:106	server will listen 0.0.0.0:8088	{"serive": "lotus_filscan"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdbed34]

goroutine 50 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Height(...)
	/opt/filscan-backend/extern/lotus/chain/types/tipset.go:136
filscan_lotus/filscaner.(*Filscaner).display_notifi_(0x257afc0, 0xc0003342c0)
	/opt/filscan-backend/filscaner/fs_loops.go:16 +0x194
filscan_lotus/filscaner.(*Filscaner).handle_new_headers(0x257afc0, 0xc0003342a0, 0x1, 0x4)
	/opt/filscan-backend/filscaner/fs_loops.go:27 +0x65
filscan_lotus/filscaner.(*Filscaner).run_syncer(0x257afc0, 0x0, 0x0)
	/opt/filscan-backend/filscaner/fs_tasks.go:32 +0x17f
filscan_lotus/filscaner.(*Filscaner).Task_StartSyncer.func1(0x257afc0)
	/opt/filscan-backend/filscaner/fs_tasks.go:56 +0x2f
created by filscan_lotus/filscaner.(*Filscaner).Task_StartSyncer
	/opt/filscan-backend/filscaner/fs_tasks.go:54 +0x5c

**Comment by onlyfor2** [comment]
大家别浪费时间了，filscan.io 是版本是V1，这个提供的是 V0，数据已经发生了很大的变化，跑起来也没有什么价值，自己搭个lotus节点，自己遍历数据吧

**Comment by Fatman13** [comment]
有没有什么别的开源软件能整理lotus api调出来的数据吗？

**Comment by hsn999** [comment]
同问，有没开源的区块浏览器
